In [1]:
import numpy as np

In [ ]:
var = np.array([1, 2, 3])
print(np.max(var),np.argmax(var)) # argmax returns the index of max number 
print(np.min(var))
print(np.mean(var))
print(np.median(var))
print(np.std(var))
print(np.var(var))
print(np.sum(var))
print(np.prod(var))
print(np.cumsum(var))


3 2
1
2.0
2.0
0.816496580927726
0.6666666666666666
6
6
[1 3 6]


In [5]:
var2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(var2, axis=0)) # max of each column
print(np.max(var2, axis=1)) # max of each row
print(np.sqrt(var2))

[4 5 6]
[3 6]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [7]:
var2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sin(var2)) # sin of each element

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
