In [1]:
import numpy as np

Arithmetic operation using numpy

In [ ]:
var = np.array([1,2,4,5,6])

varadd = var+3
print(varadd)

varmmul = var*3
print(varmmul)

vardiv = var/3
print(vardiv)

varsub = var-3
print(varsub)

varmod  = var%3
print(varmod)

varadd2 = var + varadd
print(varadd2)

[4 5 7 8 9]
[ 3  6 12 15 18]
[0.33333333 0.66666667 1.33333333 1.66666667 2.        ]
[-2 -1  1  2  3]
[1 2 1 2 0]
[ 5  7 11 13 15]


In [4]:
var1 = np.array([1,5,6,7,8,9])
var2 = np.array([2,3,4,5,6,7])

var3 = var1 + var2
print(var3)

[ 3  8 10 12 14 16]
