In [1]:
import numpy as np 

In [2]:
var = np.array([1,5,87,5,6,8,6,4,5,54,5,5,5])

for i in var:
    print(i)


1
5
87
5
6
8
6
4
5
54
5
5
5


In [12]:
var1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for j in var1:
    for k in j:
        print(k)
        print(j)

1
[1 2 3]
2
[1 2 3]
3
[1 2 3]
4
[4 5 6]
5
[4 5 6]
6
[4 5 6]
7
[7 8 9]
8
[7 8 9]
9
[7 8 9]


In [21]:
import numpy as np

var1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for i in np.nditer(var1, flags=['buffered'], op_dtypes=['int32']):
    print(i)

for i in np.ndenumerate(var1):
    print(i)

1
2
3
4
5
6
7
8
9
((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)
((2, 0), 7)
((2, 1), 8)
((2, 2), 9)
