In [ ]:
import numpy as np

Simple numpy array declaration and operations

In [ ]:
a= np.array([1,2,3,4,5])


From list to numpy array

In [ ]:
x = [1,2,3,4,5]
y= np.array(x)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [6]:
l =[]
for i in range(5):
    int_l=input("Enter a number:")
    l.append(int_l)

print(np.array(l))

['5' '5' '4' '6' '5']


Types of Array in Numpy 

In [12]:
# For checking a data type of an array we use dtype method 
ar2 = np.array([[1,2,3,4],[8,7,5,6]]) # it is 2 row and 4 column array
print(ar2.dtype)# it will show the data type of the array
print(ar2.shape)# it will show the shape of the array
print(ar2.ndim)# it will show the number of dimensions of the array

int32
(2, 4)
2


In [ ]:
arn = np.array([1,2,3,4],ndmin=10) # it will create an array with 10 dimensions
print(arn)
print(arn.ndim) # it will show the number of dimensions of the array

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Zeros

In [20]:
ar_zero = np.zeros((3,4)) # it will create an array with 3 rows and 4 columns with all values as 0
# here 3 is the no of row and 4 is the no of coloumn 
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# Array fills with Ones 

ar_one = np.ones((3,4)) # it will create an array with 3 rows and 4 columns with all values as 1
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Empty 

In [ ]:
ar_emnp = np.empty((3,4)) # it will create an array with 3 rows and 4 columns with all values as empty
print(ar_emnp)
# in this case the previous values will be store in the empty array 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Range Array 


In [24]:
ar_rn = np.arange(4)
print(ar_rn) # it will create an array with 4 values starting from 0 to 3

[0 1 2 3]


Diagonal element fills with ones 

In [28]:
ar_dia = np.eye(3,5) # it will create an identity matrix of 3 rows and 3 columns
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Line space function in numpy 

In [29]:
ar_line = np.linspace(1,10,5) # it will create an array with 5 values starting from 1 to 10
print(ar_line) # it will create an array with 5 values starting from 1 to 10

[ 1.    3.25  5.5   7.75 10.  ]


Creaying a Numpy Array with random values 

In [33]:
Var = np.random.rand(4) # it will give values between 0  and 1
print(Var)
Var1 = np.random.randn(4) # it will give values between -1 and 1
print(Var1)

[0.43313256 0.54179944 0.5490948  0.77268425]
[-2.43865018 -0.62476119 -0.02814856 -0.17436201]


Ranf() function is used to generate random numbers in a given range.

In [ ]:
var3 = np.random.ranf(4) # it will give values between 0 and 1
# it will include the values 0 but not 1
print(var3)

[0.93124087 0.59704173 0.39576223 0.98882771]


randint it generates the random number between in the given range 

In [40]:
#var4  = np.random.randint(min,max,no of values)

var4 = np.random.randint(0,10,1)
print(var4)

[6]


DATA TYPES IN NUMPY ARRAY 

In [43]:
var = np.array([1,2,3,40])
print(var.dtype) # it will show the data type of the array
var2 = np.array([1,5,4,5.5])
print(var2.dtype) # it will show the data type of the array

int32
float64


Convert the Data type 

In [44]:
x= np.array([1,5,6,4],dtype=np.int8)
print(x.dtype)

int8


In [45]:
x1= np.array([1,5,6,4],dtype="f")
print(x1.dtype)
print(x1)


float32
[1. 5. 6. 4.]


In [47]:
x= np.array([1,5,6,4])
x2 = np.float32(x)
print(x2.dtype)
print(x.dtype) # it will show the data type of the array

float32
int32


astype function is used to convert the data type of an array.

In [49]:
x3 = np.array([1,8,4,7,5,5])
x = x3.astype(float)
print(x) # it will show the data type of the array
print(x3) # it will show the data type of the array

[1. 8. 4. 7. 5. 5.]
[1 8 4 7 5 5]
