In [1]:
import numpy as np 

In [2]:
var = np.array([[1,5,6],[1,7,8]])
print(var)
print(var.shape) # (2,3)


[[1 5 6]
 [1 7 8]]
(2, 3)


In [ ]:
var1 = np.array([1,5,6,7],ndmin=5)
print(var1)
print(var1.shape) # (1, 1, 1, 1, 4) bcz 4 no of rows therefor (1,1,1,1,4) and 4 no of cloumns 

[[[[[1 5 6 7]]]]]
(1, 1, 1, 1, 4)


Reshaping and Shape of Numpy Array

In [7]:
var2 = np.array([1,8,9,5,6,4,5,6,4])

x= var2.reshape(3,3)
print(x)
print(x.shape) # (3,3) bcz 3 no of rows and 3 no of cloumns

[[1 8 9]
 [5 6 4]
 [5 6 4]]
(3, 3)


In [ ]:
var2 = np.array([1,8,9,5,6,4,5,6,4])

x= var2.reshape(-1) # -1 means it will take the no of rows automatically and 1 no of cloumns
print(x)
print(x.shape) # (9,) bcz 9 no of rows and 1 no of cloumns
print(x.ndim)

[1 8 9 5 6 4 5 6 4]
(9,)
1
