In [1]:
import numpy as np 

In [ ]:
# in slicing this is the syntax of that function 
# x[start:stop:step]

var1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
var2=var1[0:10:3]
var3 = var1[::-1] # this is used to reverse the array
print(var3)
# in this i give step 3 means it will take 3 step in above 
# example take 1 after take 4 means 3 element will take in this function
print(var2)

[10  9  8  7  6  5  4  3  2  1]
[ 1  4  7 10]


slicing in two dimesion array 

In [ ]:
var1 = np.array([[1, 2, 3,4], [4, 5, 6,4], [7, 8, 9,4]])
var2 =  var1[0:2: , 1:4] # this is used to slice the array
# array[row_start:row_end, col_start:col_end]
# in above example it takes 0 and 1 row not takes 2 and it takes 1 2 and 3 column not 4 
print(var2)

[[2 3 4]
 [5 6 4]]
